<?php
/**
 * @author      Andreas Knollmann
 * @copyright   2014-2023 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */
use Magento\Backend\Block\Template;
/** @var Template $block */
?>
<h2><?php echo $this->escapeHtml(__('Error Executing Task')); ?></h2>
<div style="font-family: 'courier new', monospace;">
    <?php echo nl2br($this->escapeHtml(trim($block->getData('reason')))); ?>
</div>
